services:
  db:
    image: postgres:15-alpine
    container_name: learn-jdbc-db
    restart: always
    environment:
      POSTGRES_USER: user2308
      POSTGRES_PASSWORD: password_rahasia
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: